### PR TITLE
Update mypy to 0.982

### LINKED ISSUE #274: Package cannot be installed along with `django-stubs==1.13.0`
# Bug report

Due to incompatible version constraint on `mypy` dependency, `djangorestfamework-stubs` cannot be installed with `django-stubs==1.13.0`.

## What's wrong

Example error from `poetry`'s resolver:
```
  SolverProblemError

  Because djangorestframework-stubs (1.7.0) depends on mypy (>=0.950,<0.970)
   and django-stubs (1.13.0) depends on mypy (>=0.980,<0.990), djangorestframework-stubs (1.7.0) is incompatible with django-stubs (1.13.0).
  So, because dcmanager depends on both django-stubs (1.13.0) and djangorestframework-stubs (1.7.0), version solving failed.
```

## How is that should be

I guess releasing a patch version of `djangorestframework-stubs` with the constraint on `mypy` matching the one of `django-stubs==1.13.0`, but I don't know what your release policy is.

## System information

- OS: doesn't matter, should be reproducible under any OS
- `python` version: 3.10
- `django` version: 4.1.3
- `mypy` version: 0.961
- `django-stubs` version: 1.13.0

### PR DESCRIPTION
**Pull request by emicba**
# I have made things!

## Related issues

Closes #274

### CODE REVIEW

**Comment by sobolevn** [comment]
Hm, there's something wrong with the CI:
> ModuleNotFoundError: No module named 'scripts'

I remember this issue, but I don't remember how to solve it :)

We did something in `django-stubs` repo 🤔

**Comment by intgr** [comment]
@sobolevn I started working on these errors in #273, but more issues popped up. I'll spend some more time on it later today.

**Comment by intgr** [comment]
FYI mypy 0.990 was released just recently.

**Comment by intgr** [comment]
@emicba I hope you don't mind if I look into the test failures and try to fix them myself. :)

**Comment by emicba** [comment]
Sure, go ahead

**Comment by emicba** [comment]
> @emicba I hope you don't mind if I look into the test failures and try to fix them myself. :)

@intgr sure, go ahead :^)

**Pull request closed without merging**
