### PR TITLE
Add GitHub actions release workflow

### PR DESCRIPTION
**Pull request by intgr**
Heavily based on the setup in `django-stubs`:

* https://github.com/typeddjango/django-stubs/pull/1950

Benefits:

* Any maintainer can make djangorestframework-stubs releases, not just me and sobolevn.
* Hopefully this will result in more frequent releases (can avoid issues like  #652).
* One fewer manual step, one less thing that can go wrong. In particular, this will prevent gaffes like #362.
* Maintainers can't inject malicious code into the PyPI release that doesn't exist in git (though we now have to trust GitHub to be not malicious).

### CODE REVIEW

**Comment by intgr** [comment]
@sobolevn needs to configure a PyPI trusted publisher, I'm guessing this should be:

> Owner: typeddjango
> Repository name: djangorestframework-stubs
> Workflow name: release.yml
> Environment name: release

(Related discussion in django-stubs: https://github.com/typeddjango/django-stubs/issues/2114)

**Comment by intgr** [comment]
Pinging @flaeppe as the author of original django-stubs release workflow.

**Review by flaeppe — APPROVED** [review]

**Comment by sobolevn** [comment]
Working on it!

**Comment by sobolevn** [comment]
Done!
Снимок экрана 2024-09-13 в 11 09 38

**Review by sobolevn — APPROVED** [review]

**Comment by intgr** [comment]
Now all we need is an excuse to make another release 😁

**Comment by browniebroke** [comment]
I saw that there was a new django-stubs release today... Would now be a good time to make a new release for drf-stubs too? 😄

**Comment by intgr** [comment]
It worked! https://github.com/typeddjango/djangorestframework-stubs/actions/runs/12329324930

**Pull request merged**
