### PR TITLE
Fix permissions, fixes #37

### LINKED ISSUE #37: Permissions aren't composable with |, &, !

### PR DESCRIPTION
**Pull request by kalekseev**
fixes #37

### CODE REVIEW

**Comment by sobolevn** [comment]
@kalekseev can you please take a look at this problem?

```
rest_framework-stubs/request.pyi: error: Source file found twice under different module names: 'rest_framework-stubs.request' and 'rest_framework.request'  [misc]

Found 1 error in 1 file (checked 48 source files)

The command "mypy -p rest_framework-stubs" exited with 2.
```

I have never seen this error before.

**Comment by kalekseev** [comment]
@sobolevn maybe when I'll have time, I don't think my changes may cause it, most probably new version of mypy or some other dep leads to that

**Comment by kalekseev** [comment]
hi @sobolevn, tests passed

**Review by sobolevn — APPROVED** [review]

**Comment by sobolevn** [comment]
Great! Thanks!

**Pull request merged**
