### PR TITLE
Python 3 8

### LINKED ISSUE #77: Support python3.8

### PR DESCRIPTION
**Pull request by morrme**
Adding support for Python 3.8. Will continue to update this as the checks run.

Fixes #77

### CODE REVIEW

**Comment by morrme** [comment]
@sobolevn Do the CI checks have to be triggered manually?

**Comment by sobolevn** [comment]
Let's try reopenning it.

**Comment by sobolevn** [comment]
Снимок экрана 2020-08-13 в 10 01 12

**Comment by sobolevn** [comment]
Travis for some reason does not like this PR.

**Comment by sobolevn** [comment]
Manual build: https://travis-ci.com/github/typeddjango/djangorestframework-stubs/builds/179533903

**Pull request merged**
