### PR TITLE
Fix typings of model meta module

### PR DESCRIPTION
**Pull request by kalekseev**

### CODE REVIEW

**Comment by kalekseev** [comment]
@sobolevn I think if you restart travis it will succeed, the fix is quite simple

**Comment by sobolevn** [comment]
@kalekseev for some reason, I cannot restart the build.

Can you please recreate this PR (or rebase/force-push it)?

**Comment by kalekseev** [comment]
@sobolevn ok, I will rebase as soon as master branch is fixed

**Comment by kalekseev** [comment]
@sobolevn thanks for fixing master, rebased pr.

**Comment by sobolevn** [comment]
@kalekseev thanks a lot for your help! 👍

**Pull request merged**
