### PR TITLE
Update MyPy max pinned version to 0.782

### PR DESCRIPTION
**Pull request by sidmitra**
- The latest version of MyPy is 0.782 [here](https://pypi.org/project/mypy/#history)

### CODE REVIEW

**Comment by sidmitra** [comment]
I've been using the latest master with 0.782 for the past few weeks and everything seems to work correctly.

**Comment by sidmitra** [comment]
Will try to take a look at the CI error later today. Not sure if it's related to the PR.

```
$ mypy -p rest_framework-stubs
rest_framework-stubs/request.pyi: error: Source file found twice under different module names: 'rest_framework-stubs.request' and 'rest_framework.request'  [misc]
Found 1 error in 1 file (checked 48 source files)
The command "mypy -p rest_framework-stubs" exited with 2.
```

**Comment by sobolevn** [comment]
Yes, this is known bug in the latest `mypy`. That's why I had to pin it to the previous version. See https://github.com/python/mypy/issues/8944

**Comment by sidmitra** [comment]
@sobolevn Thanks for the link, wasn't aware of that. I didn't come across any issues on our production codebase. I will take a deeper look, looks more involved though.

**Comment by Goldziher** [comment]
This PR can be closed @sobolevn

**Pull request closed without merging**
