### PR TITLE
Update rest_framework.schemas.openapi.ExternalDocumentationObject

### PR DESCRIPTION
**Pull request by kwang1215**
# I have made things!

### CODE REVIEW

**Review by sobolevn — COMMENTED** [review]
I don't think that this change is correct. Can you please provide a link to the source code that proves that `externalDocs` key was removed.

**Comment by kwang1215** [comment]
> I don't think that this change is correct. Can you please provide a link to the source code that proves that `externalDocs` key was removed.

I couldn't find the ExternalDocumentationObject class and externalDocs in the rest_framework/schemas/openapi.py file. However, after looking at the commit where ExternalDocumentationObject was first added, I found information related to externalDocs on https://github.com/OAI/OpenAPI-Specification.git.

Is there a connection between rest_framework/schemas/openapi.py and https://github.com/OAI/OpenAPI-Specification.git? 
I am still a beginner developer, so I'm not sure.

**Comment by sobolevn** [comment]
Yes, this is a `@type_check_only` `TypedDict` object. It represents the OpenAPI JSON spec.

**Comment by sobolevn** [comment]
I think that it is safe to close this now :)

**Pull request closed without merging**
