### PR TITLE
compatible-mypy extra

### PR DESCRIPTION
**Pull request by dimbleby**
Companion to https://github.com/typeddjango/django-stubs/pull/979

### CODE REVIEW

**Review by sobolevn — APPROVED** [review]
Thanks!

**Comment by skarzi** [comment]
hi :wave: 

When do you plan to release to PyPI a new package version with this change included? 

PS. Thanks for developing these awesome stubs!

**Comment by sobolevn** [comment]
Yes, I will soon!

**Comment by intgr** [comment]
Hi! Looking forward to a release as well. 🙏 Maybe @mkurnikov can help out again.

**Pull request merged**
