### PR TITLE
Add/improve ViewSet instance attributes

### PR DESCRIPTION
**Pull request by intgr**
Documented at https://www.django-rest-framework.org/api-guide/viewsets/#introspecting-viewset-actions

### CODE REVIEW

**Comment by intgr** [comment]
Oops, pushed a fix for this. Turns out I can't change the `as_view()` method because otherwise it would conflict with one from django-stubs. Also removed `request` attribute whcih is already defined in `View` superclass.

**Comment by intgr** [comment]
I'm really looking forward to this. :)

I use ViewSets and reference `self.action` in many places.

**Comment by sobolevn** [comment]
I am not sure about when the release will happen though

**Comment by sobolevn** [comment]
Thanks again! ;)

**Comment by intgr** [comment]
Sorry, brown paper bag moment. I somehow omitted the `action` attribute. I think I was looking up whether it's nullable or not, and got sidetracked. Now I found that there are even more instance attributes.

**Comment by sobolevn** [comment]
No problem, send one more PR.

**Pull request merged**
