### PR TITLE
CI: Run mypy on self check

### PR DESCRIPTION
**Pull request by sobolevn**

### CODE REVIEW

**Comment by intgr** [comment]
Btw if you enable this tick in repository General settings:

image

Then GitHub will present a button to merge PR branch with latest master. There are lots of times I would have found that handy, mostly when there are CI fixes in master branch.

**Comment by sobolevn** [comment]
Done

**Comment by intgr** [comment]
@sobolevn Are you already working on the type errors from CI? If not, I can take care of that part.

**Comment by sobolevn** [comment]
Nope, sorry - I don't have time for it right now.

**Review by intgr — APPROVED** [review]
It works! 🎉

**Pull request merged**
